export const ADD_EMPLOYEE ='ADD_EMPLOYEE';
export const FETCH_EMPLOYEES= 'FETCH_EMPLOYEES';
export const EDIT_EMPLOYEE= 'EDIT_EMPLOYEE';
export const DELETE_EMPLOYEE= 'DELETE_EMPLOYEE';


export const FETCH_EMPLOYEES_BEGIN   = 'FETCH_EMPLOYEES_BEGIN';
export const FETCH_EMPLOYEES_FAILURE = 'FETCH_EMPLOYEES_FAILURE';